### PR TITLE
[CGKIELE-414] documentation

### PR DESCRIPTION
**Pull request by rtkaczyk**
also fixes: CGKIELE-466

### CODE REVIEW

**Comment by brunjlar** [comment]
Hi @rtkaczyk , three questions:

- I believe in Ethereum, there is a way to call a _constant_ funtion on the local node without using a transaction and paying gas. Is that supported from `mallet` as well?
- You mention an optional list of integers as argument to `createContract` and `contractCall`. What if I have different type arguments? In particular, how do I pass in addresses as arguments? Do I still have to add `00` in front of an address to prevent it from being treated as a negative number? In that case, I think you should mention this in the documentation.
- How can I interpret return values of function calls from a receipt? I tried the `counter.sol` example, and it worked, but the return value was two bytes; the second byte was the value of my counter (as expected), but what is the first byte? In general, how are function return values encoded into a byte string?

**Comment by rtkaczyk** [comment]
@brunjlar 
1. No, there is no command for that. You could use `web3.eth.call` but requires knowledge of how to prepare the data for the function call.
2. They have to be integers because that's what IELE expects. It's up to the contract caller to express his data as integers. There can be no automatic conversion because how would we know if `'0x1234..'` is meant to be an address or a string? But I'm thinking some helper functions like `addr2int` and `str2int` could make it easier. 
    For now to pass an address you can type `0xb0ff13c14e071b11ab678524ae28e6eb248de96an` (no quotes, `n` at the end). I can't think of an easy way to convert a string.
3. The `returnData` is RLP encoded. The next PR will expose the `rlp` library. For now what you can do is:
    ```
    mallet> rlp = require('./lib/rlp.js')
    mallet> rlp.decode(getReceipt().returnData)
    ```
    Possibly a helper function should also be devised

**Comment by brunjlar** [comment]
@rtkaczyk Thanks a lot for the explanation!
One other question: You don't mention "gas price" in your examples. Is that set automatically?

**Comment by rtkaczyk** [comment]
gasPrice is 5 Gwei by default as mentioned in the code box here:

https://github.com/input-output-hk/mallet/blob/7eacdf1db99cfef53eeabbf3a1486689a9c16a06/README.md#sendtransaction

5 Gwei is a minimum requirement for the testnet, but then again it doesn't make much sense to go above that (Mantis doesn't care).

**Pull request merged**
